---
- hosts: localhost
  connection: local

  tasks:
    - name: Ensure Docker image is built from the test Dockerfile.
      docker_image:
        name: test
        source: build
        build:
          path: test
        state: present
